In [2]:
import numpy as np

from solvers.mdptoolbox_method import MdpTBSolverVI

from environments.Ex10 import Mdp

env = Mdp()

sol = MdpTBSolverVI(env)
sol.build()
sol.run()
sol.V

array([ 0.        , -1.36376048])

In [3]:
env.P

array([[[0.6, 0.4],
        [0.5, 0.5]],

       [[0.2, 0.8],
        [0.7, 0.3]]])

In [4]:
env.R

array([[ 4.5,  2. ],
       [-1.5,  3. ]])

In [4]:
from solvers.marmote import MarmoteSolverVI

sol = MarmoteSolverVI(env)
sol.build()
sol.run()
sol.policy

Restricted license - for non-production use only - expires 2024-10-28


array([0, 1], dtype=int64)

In [10]:
def compute_value(P, R, policy, gamma, epsi=1e-2):
    A, S, S = P.shape
    V = np.zeros(S)
    while True:
        delta = 0
        for s in range(S):
            v = 0
            a = policy[s]
            for prob in env.P[a, s]:
                v += 1 * prob * (R[s, a] + gamma * V[next_state])
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        if delta < epsi:
            break
    return np.array(V)

compute_value(env.P, env.R, sol.policy, 0.99)

NameError: name 'action_prob' is not defined